const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
const MODIFY_POST_REQUEST = 'MODIFY_POST_REQUEST';
const SET_MATCH_PARAMS_REQUEST = 'SET_MATCH_PARAMS_REQUEST';
const SET_POSTS_REQUEST = 'SET_POSTS_REQUEST';

export {
    ADD_POST_REQUEST,
    DELETE_POST_REQUEST,
    MODIFY_POST_REQUEST,
    SET_MATCH_PARAMS_REQUEST,
    SET_POSTS_REQUEST,
};